### ISSUE TITLE
Can't build dev container

### ISSUE THREAD

**Issue by bryanchan407** [MHSeals/ROS2-Docker-Development#11]
Tried to build on two computers, but returns this error

> Error response from daemon: unknown or invalid runtime name: nvidia
[15846 ms] Error: Command failed: docker-compose --project-name ros2-docker-development -f c:\Users\bryan\Documents\ROS2-Docker-Development\docker-compose.nvidia.yml -f c:\Users\bryan\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.build-1689450554852.yml -f c:\Users\bryan\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.containerFeatures-1689450557248.yml up -d
[15847 ms]     at Tte (c:\Users\bryan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:1972:3061)
[15847 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[15847 ms]     at async Pte (c:\Users\bryan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:1954:3170)
[15847 ms]     at async rre (c:\Users\bryan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2024:3833)
[15847 ms]     at async Yf (c:\Users\bryan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2024:4775)
[15848 ms]     at async Dne (c:\Users\bryan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2156:12193)
[15848 ms]     at async Sne (c:\Users\bryan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js:2156:11934)
[15891 ms] Exit code 1
[15909 ms] Command failed: C:\Users\bryan\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\bryan\.vscode\extensions\ms-vscode-remote.remote-containers-0.299.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\bryan\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-5f25bb3c-1346-4e3d-a156-1be5b071478b1689450540936 --workspace-folder c:\Users\bryan\Documents\ROS2-Docker-Development --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\bryan\Documents\ROS2-Docker-Development --id-label devcontainer.config_file=c:\Users\bryan\Documents\ROS2-Docker-Development\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\bryan\Documents\ROS2-Docker-Development\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 132 --terminal-rows 12
[15909 ms] Exit code 1

**Comment by alec-jensen** [comment]
Do you have an Nvidia gpu?

**Comment by bryanchan407** [comment]
> Do you have an Nvidia gpu?

my pc has one with cuda, and it didn't work. I tried it with the school laptop and it doesn't work either

**Comment by alec-jensen** [comment]
Ok what if you go to the repo folder and run `docker-compose -f docker-compose.nvidia.yml up -d`

**Comment by bryanchan407** [comment]
omg i am so stupid thank you sir alec
